name: pipeline_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython
  - numpy
  - pandas
  - gcc_linux-64  # Ensures GCC is available inside the environment
  - pip
  - pybedtools
  - bedtools
  - matplotlib
  - levenshtein
  - scikit-learn

